#privileged: true requires to specify DRONE_ADMIN=username as env variable

pipeline:
  sonar-scanner:
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    when:
      event:
        - push
        - pull_request
  slack: # pushing out notification
    image: plugins/slack:latest
    channel: dev
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
branches: master
